In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [2]:
df = pd.read_csv("student_data.csv")

In [3]:
print(df.isnull().sum())

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [4]:
df = df.drop_duplicates()

In [5]:
df.head(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [6]:
categorical_cols = df.select_dtypes(include='object').columns
print(categorical_cols)

Index(['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob',
       'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic'],
      dtype='str')

C:\Users\MD ZAID\AppData\Local\Temp\ipykernel_28256\4182786301.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns

In [7]:
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [8]:
df

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,...,guardian_mother,guardian_other,schoolsup_yes,famsup_yes,paid_yes,activities_yes,nursery_yes,higher_yes,internet_yes,romantic_yes
0,18,4,4,2,2,0,4,3,4,1,...,True,False,True,False,False,False,True,True,False,False
1,17,1,1,1,2,0,5,3,3,1,...,False,False,False,True,False,False,False,True,True,False
2,15,1,1,1,2,3,4,3,2,2,...,True,False,True,False,True,False,True,True,True,False
3,15,4,2,1,3,0,3,2,2,1,...,True,False,False,True,True,True,True,True,True,True
4,16,3,3,1,2,0,4,3,2,1,...,False,False,False,True,True,False,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,20,2,2,1,2,2,5,5,4,4,...,False,True,False,True,True,False,True,True,False,False
391,17,3,1,2,1,0,2,4,5,3,...,True,False,False,False,False,False,False,True,True,False
392,21,1,1,1,1,3,5,5,3,3,...,False,True,False,False,False,False,False,True,False,False
393,18,3,2,3,1,0,4,4,1,3,...,True,False,False,False,False,False,False,True,True,False
394,19,1,1,1,1,0,3,2,3,3,...,False,False,False,False,False,False,True,True,True,False

In [9]:
selected_columns = [
    'studytime',
    'failures',
    'absences',
    'age',
    'traveltime',
    'famrel',
    'freetime',
    'goout',
    'G1',
    'G2',
    'G3'
    
]
df = df[selected_columns]

In [10]:
df

,studytime,failures,absences,age,traveltime,famrel,freetime,goout,G1,G2,G3
0,2,0,6,18,2,4,3,4,5,6,6
1,2,0,4,17,1,5,3,3,5,5,6
2,2,3,10,15,1,4,3,2,7,8,10
3,3,0,2,15,1,3,2,2,15,14,15
4,2,0,4,16,1,4,3,2,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...
390,2,2,11,20,1,5,5,4,9,9,9
391,1,0,3,17,2,2,4,5,14,16,16
392,1,3,3,21,1,5,5,3,10,8,7
393,1,0,0,18,3,4,4,1,11,12,10
394,1,0,5,19,1,3,2,3,8,9,9

In [11]:
df.head()

,studytime,failures,absences,age,traveltime,famrel,freetime,goout,G1,G2,G3
0,2,0,6,18,2,4,3,4,5,6,6
1,2,0,4,17,1,5,3,3,5,5,6
2,2,3,10,15,1,4,3,2,7,8,10
3,3,0,2,15,1,3,2,2,15,14,15
4,2,0,4,16,1,4,3,2,6,10,10

In [12]:
df.shape

(395, 11)

In [13]:
print(df.columns)

Index(['studytime', 'failures', 'absences', 'age', 'traveltime', 'famrel',
       'freetime', 'goout', 'G1', 'G2', 'G3'],
      dtype='str')

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

X = df.drop('G3', axis=1)
y = df['G3']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = RandomForestRegressor(
     n_estimators=300,
    max_depth=10,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestRegressor(max_depth=10, n_estimators=300, random_state=42)

In [15]:
y_pred = model.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.8490500340786129

In [16]:
y_pred

array([ 8.48577273, 11.70038918,  6.86666667,  9.6139552 ,  9.128147  ,
       13.05880952, 19.02333333,  6.96627778,  6.75455026, 12.55039683,
       15.57833333,  7.39905556, 14.24      , 11.83667273, 14.13633333,
        8.31190768,  2.50333333, 10.35499811, 15.12394775,  4.06398226,
       13.60977778, 15.53316667, 15.05140807,  6.86361111,  7.119375  ,
       18.53      , 10.67861111, 10.46488935, 18.05315789, 10.87965314,
        8.93835095,  8.83103724, 15.16150331, 13.23692063,  1.75666667,
        6.61333333,  0.02      , 15.19708267, 11.88455286,  7.98378116,
        5.92      , 10.59663889, 13.95833333,  9.02525144, 15.45837271,
        9.8223181 , 12.01814033, 13.99416667, 12.41666667, 15.4013097 ,
       13.20188889, 14.70539219, 10.65810714,  9.65010223,  6.34      ,
       13.25583333, 10.85912195,  1.98666667, 15.90855556, 16.10555556,
       13.31669192,  9.54557636,  8.22543383,  5.81714286,  7.80544444,
       17.95      ,  8.7896197 ,  9.79087864,  8.97321508, 15.54494065,
        8.51499976,  9.54940171, 13.51573545, 18.45666667, 10.74066667,
        5.89027778,  9.34162121, 14.05633333,  5.30333333])

In [17]:
with open("model.pkl", "wb") as file:
    pickle.dump(model, file)

In [18]:
print(model.n_features_in_)

10

In [19]:
print(X.columns.tolist())

['studytime', 'failures', 'absences', 'age', 'traveltime', 'famrel', 'freetime', 'goout', 'G1', 'G2']